### ISSUE TITLE
系统是不是不支持商户自己的管理员登录

### ISSUE THREAD

**Issue by shuangg** [yybawang/laravel-ebank#3]
允许一个用户查看/管理一个或多个指定商户的交易设置和交易记录
从管理界面和代码来看来看似乎没有这个功能
数据里也只有admin而没有user
并且admin用户和merchant没有关联

**Comment by yybawang** [comment]
没有这个功能，这个属于总后台，二级商户的业务每个项目都不一样，再怎么做也不会满足你们下级业务逻辑的，所以须自己开发。

**Comment by yujiye** [comment]
大神,我到处找你^....加个微信可好?
yujiye2011
1294983@qq.com...
盼望你的金光笼罩我
